version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
      - "5678:5678" 
    environment:
      - NEO4J_URI=neo4j+s://33e44caf.databases.neo4j.io
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python app.py