# fly.toml app configuration file generated for graphrag-u0roxq on 2025-04-30T11:27:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'graphrag-u0roxq'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
